name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'thetaplatformuiinstrumentsapi:$(build.buildNumber)'

steps:
- script: docker build -f Theta.Platform.UI.Instruments.API/Dockerfile -t $(imageName) .
  displayName: 'docker build'
  workingDirectory: 'src'