name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)

resources:
  containers:
    - container: build_container
      image: ubuntu:16.04

variables:
  imageName: 'thetaplatformuiinstrumentsapi:$(build.buildNumber)'

trigger:
  paths:
    include:
      - src/Theta.Platform.UI.Instruments.API/*

steps:
- script: docker build -f Theta.Platform.UI.Instruments.API/Dockerfile -t $(imageName) .
  displayName: 'docker build'
  workingDirectory: 'src'