apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-secret
spec:
  secretName: tls-secret
  dnsNames:
  - theta-{environment}.{region}.cloudapp.azure.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - theta-{environment}.{region}.cloudapp.azure.com
  issuerRef:
    name: letsencrypt-{letsencryptEnvironment}
    kind: ClusterIssuer