apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-{letsencryptEnvironment}
spec:
  acme:
    server: {letsencryptServer}
    email: {acmeEmail}
    privateKeySecretRef:
      name: letsencrypt-{letsencryptEnvironment}
    http01: {}