name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'thetaplatformuipricingstreaming:$(build.buildNumber)'

trigger:
  branches:
    include:
    - '*'
  paths:
    include:
    - src/Theta.Platform.UI.Pricing.Streaming/*

steps:
- script: docker build -f Theta.Platform.UI.Pricing.Streaming/Dockerfile -t $(imageName) .
  displayName: 'docker build'
  workingDirectory: 'src'