version: '3.4'

services:
  event.store:
    image: eventstore/eventstore
    networks:
      theta-service-net:
        aliases:
          - event.store

  theta.platform.ui.instruments.api:
    image: thetaplatformuiinstrumentsapi
    networks:
      theta-service-net:
        aliases:
          - theta.platform.ui.instruments.api
    build:
      context: .
      dockerfile: Theta.Platform.UI.Instruments.API/Dockerfile
      args:
        Version: 0.0.1-dev

  theta.platform.ui.pricing.streaming:
    image: thetaplatformuipricingstreaming
    networks:
      theta-service-net:
        aliases:
          - theta.platform.ui.pricing.streaming
    build:
      context: .
      dockerfile: Theta.Platform.UI.Pricing.Streaming/Dockerfile
      args:
        Version: 0.0.1-dev
    depends_on:
      - theta.platform.ui.instruments.api

  theta.platform.ui.orders.api:
    image: thetaplatformuiordersapi
    networks:
      theta-service-net:
        aliases:
          - theta.platform.ui.orders.api
    build:
      context: .
      dockerfile: Theta.Platform.UI.Orders.API/Dockerfile
      args:
        Version: 0.0.1-dev
    depends_on:
      - event.store

  theta.platform.order.management.service:
    image: thetaplatformordermanagementservice
    networks:
      theta-service-net:
        aliases:
          - theta.platform.order.management.service
    build:
      context: .
      dockerfile: Theta.Platform.Order.Management.Service/Dockerfile
      args:
        Version: 0.0.1-dev
    depends_on:
      - event.store

  theta.platform.rfq.management.service:
    image: thetaplatformrfqmanagementservice
    networks:
      theta-service-net:
        aliases:
          - theta.platform.rfq.management.service
    build:
      context: .
      dockerfile: Theta.Platform.RFQ.Management.Service/Dockerfile
      args:
        Version: 0.0.1-dev
    depends_on:
      - event.store

networks:
  theta-service-net:
    driver: bridge