version: '3.4'

services:
  event.store:
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=System
      - EVENTSTORE_MEM_DB=True 
      - EVENTSTORE_START_STANDARD_PROJECTIONS=True 
      - EVENTSTORE_EXT_TCP_HEARTBEAT_TIMEOUT=30000
    ports:
      - "2113:2113"
      - "1113:1113"

  theta.platform.ui.pricing.streaming:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=15102
    ports:
      - "15101:80"
      - "15102:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  theta.platform.ui.orders.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=15104
    ports:
      - "15103:80"
      - "15104:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  theta.platform.ui.instruments.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=15106
    ports:
      - "15105:80"
      - "15106:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  theta.platform.order.management.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=15108
    ports:
      - "15107:80"
      - "15108:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
