kind: Service  
apiVersion: v1  
metadata:  
  name: "frontend-es"
spec:  
  selector:
    app: "frontend-es"
  ports:
    - protocol: "TCP"
      port: 2113
      targetPort: 2113
  type: LoadBalancer