kind: Service  
apiVersion: v1  
metadata:  
  name: "event-store-frontend"
spec:  
  selector:
    app: "event-store-frontend"
  ports:
    - protocol: "TCP"
      port: 2113
      targetPort: 2113
  type: LoadBalancer